pipeline:
  identifier: Build_alejandrosoto27_jhttp_1727098001491
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: Lab
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: alejandrosoto27/jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: build_java_app
                  name: Build Java App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
                  type: Run
              - step:
                  name: HelloWorldTemplate
                  identifier: HelloWorldTemplate
                  template:
                    templateRef: Hello_World_Step_Template
                    versionLabel: v1
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
